### ISSUE TITLE
Slow Startup Time (~200-300ms Delay) Before Window Appears

### ISSUE THREAD

**Issue by iyiolacak** [Skxxtz/sherlock#25]
**There is a noticeable delay of approximately 200-300 milliseconds** between pressing the keybinding to launch Sherlock and the window actually becoming visible on screen. This makes the launcher feel sluggish compared to alternatives like Wofi, which appear nearly instantaneously.

## Expected Behavior
Sherlock should appear almost immediately after its launch keybinding is pressed, similar to other lightweight launchers.

## Actual Behavior
A consistent delay of ~200-300ms occurs before the Sherlock UI is rendered and displayed.

## Steps to Reproduce
1. Bind Sherlock launch to a key (e.g., SUPER+D)
2. Press the keybinding
3. Observe the delay before the window appears

### ~/.config/sherlock/fallback.json
```json
[
    {
        "name": "App Launcher",
        "alias": "app",
        "type": "app_launcher",
        "args": {},
        "priority": 2,
        "home": true
    }
]
```

### ~/.config/sherlock/config.toml (Behavior Section)
```toml
[behavior]
caching = true # Tried false as well.
# cache = ...
daemonize = false # !! NOTE: "Daemonize true" breaks Sherlock. Even turning `daemonize` off back, makes Sherlock not work/appear unless I processkill `Sherlock`.
# ...
```

## Attempted Troubleshooting
- Confirmed the delay persists even with the minimal fallback.json containing only app_launcher
- Tested deleting the application cache (~/.cache/sherlock_desktop_cache.json); the delay remained similar on subsequent launches

## System Information
- Sherlock Version: Sherlock v0.1.9
- Operating System: Fedora 41
- Window Manager: Hyprland
- CPU: Intel Core i7 10th gen
- Disk Type: SSD
- Graphics Card: NVIDIA GeForce RTX 2060 - Mobile(Laptop)
- Graphics Driver: NVIDIA-SMI 570.133.07, Driver Version: 570.133.07, CUDA Version: 12.8
➜ Hyprland --version
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2
