### ISSUE TITLE
Theming with PyWal is impossible

### ISSUE THREAD

**Issue by TheElevatedOne** [Skxxtz/sherlock#31]
I am trying to use your tool in my rice and I am using [pywal](https://github.com/dylanaraps/pywal) for colors.

Your themes use HSL and pywal uses HEX.

The gtk css does not seem to support css functions, so I cannot convert.

This is a pywal colors file:
```css
:root {
    --wallpaper: url("/home/the-elevated-one/Pictures/Wallpapers/orion-what-the-hell.jpg");

    /* Special */
    --background: #0c0a0c;
    --foreground: #b0bccc;
    --cursor: #b0bccc;

    /* Colors */
    --color0: #0c0a0c;
    --color1: #7c00b3;
    --color2: #e30077;
    --color3: #006fc2;
    --color4: #1f00f7;
    --color5: #ff06dd;
    --color6: #ff3a9d;
    --color7: #b0bccc;
    --color8: #7b838e;
    --color9: #7c00b3;
    --color10: #e30077;
    --color11: #006fc2;
    --color12: #1f00f7;
    --color13: #ff06dd;
    --color14: #ff3a9d;
    --color15: #b0bccc;
}
```

How do I make it work with your software?

EDIT: Background is transparent after I tried.
Cannot fix it.

![Image](https://github.com/user-attachments/assets/693e51de-1b7b-4103-9759-cf563dfaa564)
