### ISSUE TITLE
Unable to disable animations

### ISSUE THREAD

**Issue by poach3r** [Skxxtz/sherlock#70]
### Description
Animations are not disabled after setting `config.behavior.animate` to `false`. I also tried setting `config.appearance.animate` to `false` as `animate` used to be in `appearance`, however this didn't work. The following is the relevant portion of my config:
```toml
[behavior]
cache = "~/.cache/sherlock/sherlock_desktop_cache.json"
caching = true
daemonize = false
animate = false
```

### Steps to Reproduce
1. Set `config.behavior.animate` to `false` within `sherlock/config.toml`
2. Open Sherlock using the `sherlock` command

### Expected Behavior
All animations within the program are disabled.

### Environment
- Operating System: Arch Linux
- Kernel: 6.14.3-arch1-1
- Window Manager: Wayfire
- Version: 0.1.11

**Comment by Skxxtz** [comment]
Hi there, the 'animate' key is deprecated since 0.1.10. However, all animations, except for the loading spinner in the status bar, can be disabled in the css

**Comment by poach3r** [comment]
Thanks, I'll take a look at it.

**Comment by poach3r** [comment]
Apologies for reopening this issue, however I cannot seem to disable animations with CSS. I've tried adding the following to no avail:
```css
window {
    transition: none;
    animation: none;
    transition-duration: 0s;
    transition-timing-function: linear;
}
```
